### ISSUE TITLE
Missing some export in index.ts

### ISSUE THREAD

**Issue by ioull** [Salamek/huawei-lte-api-ts#1]
I try use it from Nodered it is full functionnel for Devices but it is not working for SMS
perhaps because some export are missing in export.ts like :
export * from './api/SMS';
Not sure about that as I don't speak typscript / javascript fluently ;-)

**Comment by Salamek** [comment]
Well this lib is a port of https://github.com/Salamek/huawei-lte-api to TS, so i suggest to use that project if possible...
If you need to use this TS/JS library, PRs with fixes are welcomed
