### ISSUE TITLE
How can I pass a parameter in the DialUp.dial() method ?

### ISSUE THREAD

**Issue by marcSitze** [Salamek/huawei-lte-api-ts#13]
Hello, I'm very happy and excited since I have seen this repo,

please I wish to pass some parameters in the DialUp.dial() method, something like DialUp.dial('#123#') for example, I have browsed all the documentation but it seems like there's no method for that, 

thanks for your concern and I hope for a favorable response

**Comment by Salamek** [comment]
Well does your router support something like that^ in its web GUI?

**Comment by marcSitze** [comment]
Hello, sorry for my late reply

I don't really know but my router is a Huawei B310s-22, 
I saw this package which implements ussd methods but my problem is that it's written in python
https://github.com/pablo/huawei-modem-python-api-client, I would have really appreciate if it was a nodejs based project just like yours

**Comment by zinen** [comment]
Looking into [src/api/DialUp.ts](https://github.com/Salamek/huawei-lte-api-ts/blob/57ebf09da2ba330ea9c8a6b4195c2319f3d1ebb6/src/api/DialUp.ts#L28) I would guess something like this should work. But my router just respond back with OK when I run this code but nothing happened.

```js
const huaweiLteApi = require('huawei-lte-api')
async function start() {
    try {
        const connection = new huaweiLteApi.Connection('http://admin:password@192.168.8.1/')
        await connection.ready
        const dialUp = new huaweiLteApi.DialUp(connection)
        const result = await dialUp.dial('#123#')
        console.log(result)
    } catch (error) {
        console.error('Ended in error:')
        console.error(error)
    }
}
start()
```

**Comment by Salamek** [comment]
@zinen dialUp.dial has no parameter/s implemented... and i don't think that it can be used in that way :/

@marcSitze well my B310s-22 does not support that ussd endpoint in library you have provided so there is that...

If someone finds how to send ussd commands via HTTP API to huawei router, i will gladly implemented it... only way i have seen USSD work is using AT commands when connected directly via USB (USB modems in modem mode)

**Comment by marcSitze** [comment]
@Salamek  alright I understand thanks for your concern, I will be listening for updates concerning USSD commands
