### ISSUE TITLE
3372h-320 (send-sms) seems like it needs encryption??

### ISSUE THREAD

**Issue by grawsom** [Salamek/huawei-lte-api-ts#15]
Why I'm writing here is because I wanted to use the 3372 in Node-red, and [this one](https://github.com/zinen/node-red-contrib-huawei-router) have made a Node-red package that uses you API - but.

Seems like the 3372h-320 need some encryption when doing some sms stuff, for me it's send-sms.

Maybe [this one](https://github.com/vzakharchenko/huawei-hilink) could help, because the send-sms works with this package, and what I can see is that in the source is some `<nonce>${encrpt}</nonce>` after date in the URL when calling the API.

If I can help some way in testing with my device I'm here :-)

**Comment by Salamek** [comment]
@grawsom try 0.0.9 pls

**Comment by grawsom** [comment]
@Salamek  Sorry - No change.
Here is the output
`Ready
ResponseErrorException: 100005: Unknown
    at new ResponseErrorException (C:\Users\ivans\.node-red\node_modules\huawei-lte-api\dist\exceptions.js:22:28)     
    at Connection.checkResponseStatus (C:\Users\ivans\.node-red\node_modules\huawei-lte-api\dist\Connection.js:168:19)
    at C:\Users\ivans\.node-red\node_modules\huawei-lte-api\dist\Connection.js:308:54
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 100005
}`

I have again made some wireshark saves, (send_sms.js, device_info.js) and the working sh script (script.sh)
[0.0.9.zip](https://github.com/Salamek/huawei-lte-api-ts/files/7762574/0.0.9.zip)

**Comment by Salamek** [comment]
@grawsom #17 by @icetee fixes this issue, just tested on my 3372h-320 (i remembered i have like a week ago lol)
So pls install 0.0.10 to test
